### ISSUE TITLE
249: Convert materials and textures

### ISSUE THREAD

**Issue by tngreene** [X-Plane/XPlane2Blender#425]
Convert materials and texture settings to XPlane2Blender

[wiki-page](https://github.com/der-On/XPlane2Blender/wiki/249:-How-It-Works:-Materials)

- [x] Research how XPlane2Blender used Materials and Textures
- [x] Collect Used Buttons
- [x] Get proof of concept working

# Progress Report

Main Quests
- [x] Break a mesh with non-uniform face buttons,
- [x] materials,
- [x] and use of panel texture on face
into smaller separate meshes before conversion.

- [x] Get TEX, TILES and LIGHT (and, honestly, when it is working, all the TexFace Buttons) from the MTexPoly.flag or MTFace.flag by using ctypes (MTFace might be deprecated, or a copy? but it doesn't matter because 2.8 also drops this? Maybe?)
- [x] Implement ATTR_shadow (#427)

**Comment by tngreene** [comment]
Q: How do we get the Texture Face Flag if it isn't exposed in the Python API and gets messed with in `encode_tfaceflag`?
A: Horrible answer it looks like we're going to have to use: ctypes!

`bpy.data.objects['Cube'].data.as_pointer()` returns a pointer to the start of a `typedef struct Mesh` from "DNA_mesh_types.h". We can copy this data structure as a Python ctypes.Structure, then read MTFace's flag and mode members directly.

This is, I think, the only possible way to accomplish this and it absolutely won't work for 2.8. I think if we're going to do this, we should bump the minimum version to 2.79 so we don't have to worry about data layout differences.

**Comment by tngreene** [comment]
# Progress Report

Main Quests
- [ ] Break a mesh with non-uniform face buttons into smaller separate meshes before conversion.
- [ ] Get TEX, TILES and LIGHT (and, honestly, when it is working, all the TexFace Buttons) from the MTFace.flag by using ctypes (see above)
- [ ] Implement ATTR_shadow (#427)

**Comment by tngreene** [comment]
Newly discovered issue:

Suppose:

CubeA with material 'Material1', who's TexFace property for Dynamic is **Pressed**
and
CubeB with material 'Material1', who's TexFace property for Dynamic is **Not Pressed**

The expectation is that CubeA and CubeB have different values for Dynamic, but in actuality, Blender 2.79 reports the mode and Phyics button as the same value.

When CubeB is given 'Material2' with the same TexFace properties, the expected happens. We're going to have to take from the face properties always as opposed to only when they're different.

**Comment by tngreene** [comment]
Polish moment:

Suppose a mesh of 3 planes, each to be split into their own object, but no materials present. Currently, at the end of this process you'll wind up with 3 objects with 3 material slots each
```
Cube1: 249_COLL, 249, 249
Cube2: 249_INVIS, 249, 249
Cube3: 249_TEX_ALPHA, 249, 249
```
Why? Because Blender's converter automatically created 3 materials for the faces of Cube. The converter replaces them all with 249. (This, is actually okay! We've already saved the TF_modes_and_their_faces before the materials with default names got replaced!) We only pay attention to the first material slot anyway, but, it would be nice to have as minimal as possible, since this wasn't a user's choice

**Comment by tngreene** [comment]
All checkboxes are checked! Closed!

There are still several TODOs in the code, however:
- [ ] Getting rid of The above polish moment
- [ ] Deciding what to do about this case:
```
                    #TODO: But what about `NoSplit` with Materials A, B, and C? What should go here?
                    #TODO: After split, number of Materials should only include what is needed
                    #TODO: What about slots [None, Material.TF.135]?
```
- [ ] Cleaning up print statments and making logger statements instead. See #402
- [ ] #444 Scenery specific material props

but these can wait till later. Splitting and the basics are done!
