### ISSUE TITLE
Importer. (yes. seriously.)

### ISSUE THREAD

**Issue by tngreene** [X-Plane/XPlane2Blender#610]
> It has been decided that XPlane2Blender should have an importer to migrate old .obj files that came from other editors besides Blender 2.49. Also people have asked me "Where is the import function? The name is _____2Blender after all" for long enough. Also people keep rewriting the name as "Blender2XPlane" in e-mails to be helpful when I find that it isn't. So here we are. Importer. If people want to talk about DRM, encryption, and protection, this is not the place for it and know I have no control over any of that. So! Here we go. 6 years after XPlane2Blender for modern Blender started.

# XPlane2Blender Importer
This importer targets importing .obj files
- Regardless of their previous exporter (including hand written content)
- To the best of its ability to (saving what it can and using reasonable defaults)
- Ignoring deprecated and bad practices
- While attempting to translate those deprecated and bad practices to modern good practices
- Invalid data is labeled and organized, but not dropped
- Results get put into a log

It aims to make instantly exportable projects, but are satisfied making "getting enough right to let you put the pieces back together. It doesn't offer 1:1 round trip between export and import nor will it recreate project layouts.

The importer will not drive the design of the exporter, since the exporter is what chiefly makes new content.

Just like the exporter hopefully the importer is a one button no configuration or interactive steps

# Road map
- [ ] Figure out new unit test template for this
- [ ] File parser respecting the OBJ8 spec, but also knowing how loose it can be
- [ ] Collecting small and medium samples from various other exports, including Blender 2.49, AC3D, 3DsMax, and even XPlane2Blender 3.3.0
- [ ] Separate the VT table back into meshes
- [ ] Log of errors, warnings, and infos
- [ ] Collect and apply animations
- [ ] Collect lights
- [ ] Apply manipulators
- [ ] Apply material attributes again
- [ ] A billion other little attributes I'm sure we'll get into

This bug represents the master list. Labels, milestones, will also track this.

Time to complete: much less than the converter!

**Comment by arb65912** [comment]
It is definitely a very big deal but if I had a say in it I would rather have exporter released before starting importer. I understand it is a personal preference though.

**Comment by tngreene** [comment]
Don't worry, v4.1.0 is basically done. As long as this beta goes well v4.1.0 will be counted as rc1.

**Comment by arb65912** [comment]
That is great news Ted! Thanks.

**Comment by tngreene** [comment]
(and it isn't much of a personal preference either. Its a Ben preference. Anytime he's said "what do you think?" we come up the same priorities anyway :) )

**Comment by arb65912** [comment]
Understood :-)

**Comment by tngreene** [comment]
![image](https://user-images.githubusercontent.com/5393207/99864056-3e35a780-2b6f-11eb-8cde-bc6621733615.png)
And so the madness begins

**Comment by DWmFrancis** [comment]
As long as .fbx is on the formats and it brings across the textures from Fusion 360, I’m *very* happy.

-df

**Comment by todirbg** [comment]
You may know that there are 2 or 3 importer projects on GitHub and they do pretty good job importing meshes, but it seems that the problem is importing animations, especially stacked ones. I cant even try to imagine how are you going to tackle the problem having many different ways to animate an mesh in blender.

**Comment by tngreene** [comment]
(Cause we have a secret weapon that no one else has: Ben can do some of the math. I kid.) I'm not sure, but it'll get figured out! I have seen some of the importers, but I haven't read the source code in detail.

As mentioned, one thing I'm not trying for is making a perfectly exportable project the first pass around. If there's some garbled confusing stuff it'll get imported with a note on what to fix. As a lesson learned from the converter trying to be perfect is the enemy of having it work at all in a reasonable amount of time. And with this there are simply too many inputs.

So: simply: It'll be made to work!
